### ISSUE TITLE
Add example using serde_json::from_reader or serde_json::Deserializer::from_reader

### ISSUE THREAD

**Issue by dtolnay** [tmccombs/json-comments-rs#1]
The existing example code on the strip_comments function shows read_to_string only. It would be good to show the other common way that this library would be used which is deserializing json directly from the StripComments stream via from_reader.

@tmccombs

**Comment by dtolnay** [comment]
Once there is example code, I can link to it when people ask about comments in serde_json.

**Comment by tmccombs** [comment]
This is fixed by f1597efa4bbdcc1cfd7f24a45e55c5952bad0506
