### ISSUE TITLE
Support docblock comment styles

### ISSUE THREAD

**Issue by milesj** [tmccombs/json-comments-rs#12]
Would be great if this lib also supported stripping `/** **/` styled docblock comments, instead of just `/* */`.

For example:

```
/** This doesn't work **/
{
  "compilerOptions": {
    "noEmit": true
  }
}
```

**Comment by milesj** [comment]
@tmccombs I'd be willing to contribute, but not really sure where to start. Any suggestion?

**Comment by tmccombs** [comment]
This was a bug. After a little debugging with gdb I found the problem.

**Comment by milesj** [comment]
Awesome, thanks!
