### ISSUE TITLE
Configuring which kinds of comments to support

### ISSUE THREAD

**Issue by LPGhatguy** [tmccombs/json-comments-rs#7]
Hello! Thank you for this crate, it's very neat and works well as far as I've tested.

One use case for this library is as a holdover until the Rust [JSON5](https://github.com/callum-oakley/json5-rs) and [JSONC](https://github.com/dprint/jsonc-parser) implementations are more mature. Both of those specifications have more features than just comments, but to me, comments are the biggest improvement that can be made!

Neither JSON5 nor JSONC support comments starting with `#`. It would be useful to be able to turn off that feature of this library, to keep those as syntax errors. This is important to me as an author of a project with stable configuration files -- if I move from `json_comments` to `json5` or `jsonc` in the future, I want all existing files to stay compatible!

**Comment by tmccombs** [comment]
I added support for that. Hopefully that works for you. Sorry it took me so long to get to this.

**Comment by LPGhatguy** [comment]
Thank you! This is actually still very relevant for me, so I appreciate the work done here. 😀

There's no need to apologize for a delay. You're providing everyone a useful, free project already!
